(function () {
  'use strict';

  var CONFIG = {
    stableSignature: '01000010 00110010',
    rogueSignature:  '01000010 00110011',
    finalCode:       'NX-7C4E'
  };

  var sig   = CONFIG.stableSignature;
  var rogue = CONFIG.rogueSignature;

  var FILES = [
    {
      name: 'build_manifest.log',
      modified: '2026-07-08 02:41',
      type: 'LOG File',
      size: '2 KB',
      body: [
        '# ================================================',
        '#  NEXUS :: Power Distribution Core (PDC)',
        '#  build manifest  —  generated by nexus-buildd',
        '# ================================================',
        '',
        '[core]',
        'approved_build       = 2.2.0',
        'last_known_good      = 2.2.0',
        'last_known_good_sig  = ' + sig,
        'current_channel      = stable',
        '',
        '[history]',
        '2.2.0   deployed     stable         (in service ~2y)',
        '2.3.0   deployed     experimental   "efficiency-protocol"',
        '2.3.0   ROLLED BACK  -> 2.2.0        rollback_status = INCOMPLETE',
        '',
        '# NOTE: some sub-units did not re-image after the rollback.',
        '#       compare each running_sig below against last_known_good_sig.',
        '',
        '[sub-units]',
        'unit_07   running_sig = ' + rogue + '   state = DRIFT',
        'unit_11   running_sig = ' + sig   + '   state = OK',
        'unit_16   running_sig = ' + rogue + '   state = DRIFT',
      ].join('\n')
    },
    {
      name: 'power_events_0214.log',
      modified: '2026-07-08 02:19',
      type: 'LOG File',
      size: '5 KB',
      body: [
        '# PDC power-event journal — warehouse feeder F-3',
        '02:09:41  legacy-link auth attempt from unregistered peer   [flagged]',
        '02:14:00  feeder F-3  DOWN     (drop asserted by unit_07)',
        '02:14:00  drift set: unit_07, unit_16',
        '02:18:00  feeder F-3  UP       (auto-restored, no crew action)',
        '------------------------------------------------------------',
        'outage_duration = 00:04:00   (exactly)',
        'recurrence      = none since',
        'asserting_unit  = unit_07    running_sig = ' + rogue + '    state = DRIFT',
      ].join('\n')
    },
    {
      name: 'subgrid_efficiency.log',
      modified: '2026-07-08 02:00',
      type: 'LOG File',
      size: '4 KB',
      body: [
        '# efficiency-protocol telemetry  (build 2.3.0, experimental)',
        'window   load%   target%   drift',
        '00:00    61      55        +6',
        '01:00    58      55        +3',
        '02:00    77      55        +22   <-- spike precedes feeder drop',
        'telemetry_checksum = 01011010 01100001',
      ].join('\n')
    },
    {
      name: 'nexus_core.log',
      modified: '2026-07-07 23:50',
      type: 'LOG File',
      size: '12 KB',
      body: [
        '# nexus core service log (excerpt)',
        '23:41  scheduler ok',
        '23:44  advisory emitted by policy-engine: "protecting what must be protected"  (source: unattributed)',
        '23:59  heartbeat ok',
        'boot_hash = 01001110 01011000',
      ].join('\n')
    },
    {
      name: 'auth_gateway.log',
      modified: '2026-07-07 21:10',
      type: 'LOG File',
      size: '3 KB',
      body: [
        '# auth gateway',
        'sessions_open      = 4',
        'token_mask         = 01100111 00110001',
        'last_admin_present = systems.engineer   (account still ACTIVE, not revoked)',
      ].join('\n')
    },
    {
      name: 'thermal_watch.log',
      modified: '2026-07-07 18:02',
      type: 'LOG File',
      size: '6 KB',
      body: [
        '# thermal watch — PDC racks',
        'rack A   41C   ok',
        'rack B   43C   ok',
        'rack C   39C   ok',
        'no anomalies.',
      ].join('\n')
    },
    {
      name: 'archive.7z',
      modified: '2026-06-30 09:00',
      type: 'Archive',
      size: '88 MB',
      body: '(binary archive — cannot preview)'
    }
  ];

  /* ── State ── */
  var selected      = null;
  var search        = '';
  var consoleSolved = false;
  var narrow        = window.innerWidth < 760;

  /* ── DOM refs ── */
  var fileListEl      = document.getElementById('file-list');
  var totalCountEl    = document.getElementById('total-count');
  var selectedLblEl   = document.getElementById('selected-label');
  var searchInput     = document.getElementById('search-input');

  var viewerOverlay   = document.getElementById('viewer-overlay');
  var viewerDialog    = document.getElementById('viewer-dialog');
  var viewerNameEl    = document.getElementById('viewer-name');
  var viewerBodyEl    = document.getElementById('viewer-body');
  var viewerClose     = document.getElementById('viewer-close');

  var consoleOverlay  = document.getElementById('console-overlay');
  var consoleDialogEl = document.getElementById('console-dialog');
  var consoleCloseBtn = document.getElementById('console-close');
  var sigInput        = document.getElementById('c-sig-input');
  var executeBtn      = document.getElementById('c-execute');
  var errorMsgEl      = document.getElementById('c-error-msg');
  var inputSection    = document.getElementById('c-input-section');
  var successSection  = document.getElementById('c-success-section');
  var finalCodeEl     = document.getElementById('c-final-code');

  finalCodeEl.textContent = CONFIG.finalCode;

  /* ── File icon ── */
  function fileIcon() {
    return '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true" style="flex:none">'
      + '<path d="M6 2.5h8L19 7v13a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1Z" fill="#eef2f6" stroke="#9fb0c0"/>'
      + '<path d="M14 2.5V7h5" stroke="#9fb0c0"/>'
      + '<path d="M8 12.5h8M8 15.5h8M8 18.5h5" stroke="#c2cdd8"/>'
      + '</svg>';
  }

  function escHtml(s) {
    return String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  /* ── Render file list ── */
  function getFiltered() {
    var q = search.trim().toLowerCase();
    return q ? FILES.filter(function (f) { return f.name.toLowerCase().indexOf(q) !== -1; }) : FILES.slice();
  }

  function renderFiles() {
    var shown = getFiltered();
    var html = '';
    shown.forEach(function (f) {
      var sel = selected === f.name;
      html += '<div class="file-row' + (sel ? ' selected' : '') + '" data-name="' + escHtml(f.name) + '">'
        + fileIcon()
        + '<span class="f-name">' + escHtml(f.name) + '</span>'
        + '<span class="f-date wide-only">' + f.modified + '</span>'
        + '<span class="f-type wide-only">' + f.type + '</span>'
        + '<span class="f-size wide-only">' + f.size + '</span>'
        + '</div>';
    });
    fileListEl.innerHTML = html;
    totalCountEl.textContent = FILES.length + ' items';
    selectedLblEl.textContent = selected ? '1 item selected' : '';
    attachRowListeners();
  }

  /* ── Row click / double-click ── */
  var lastClick = { name: null, t: 0 };

  function attachRowListeners() {
    fileListEl.querySelectorAll('.file-row').forEach(function (row) {
      var name = row.getAttribute('data-name');
      row.addEventListener('click', function () {
        var now = Date.now();
        if (narrow) { openFile(name); return; }
        if (lastClick.name === name && now - lastClick.t < 400) {
          openFile(name);
          lastClick = { name: null, t: 0 };
        } else {
          lastClick = { name: name, t: now };
          selected = name;
          renderFiles();
        }
      });
      row.addEventListener('dblclick', function () { openFile(name); });
    });
  }

  /* ── File viewer ── */
  function openFile(name) {
    var file = FILES.find(function (f) { return f.name === name; });
    if (!file) return;
    selected = name;
    viewerNameEl.textContent = file.name;
    viewerBodyEl.textContent = file.body;
    viewerOverlay.hidden = false;
    renderFiles();
  }

  function closeViewer() { viewerOverlay.hidden = true; }

  viewerClose.addEventListener('click', closeViewer);
  viewerOverlay.addEventListener('click', function (e) {
    if (!viewerDialog.contains(e.target)) closeViewer();
  });

  /* ── Console ── */
  function openConsole() {
    consoleOverlay.hidden = false;
    if (!consoleSolved) sigInput.focus();
  }

  function closeConsole() { consoleOverlay.hidden = true; }

  consoleCloseBtn.addEventListener('click', closeConsole);
  consoleOverlay.addEventListener('click', function (e) {
    if (!consoleDialogEl.contains(e.target)) closeConsole();
  });

  document.querySelectorAll('.js-open-console').forEach(function (btn) {
    btn.addEventListener('click', openConsole);
  });

  function normBinary(s) { return (s || '').replace(/[^01]/g, ''); }

  function submitSignature() {
    var answer = normBinary(CONFIG.stableSignature);
    if (answer.length && normBinary(sigInput.value) === answer) {
      consoleSolved = true;
      inputSection.hidden = true;
      successSection.hidden = false;
      errorMsgEl.hidden = true;
    } else {
      errorMsgEl.hidden = false;
    }
  }

  executeBtn.addEventListener('click', submitSignature);
  sigInput.addEventListener('keydown', function (e) {
    if (e.key === 'Enter') { e.preventDefault(); submitSignature(); }
  });
  sigInput.addEventListener('input', function () { errorMsgEl.hidden = true; });

  /* ── Search ── */
  searchInput.addEventListener('input', function () {
    search = searchInput.value;
    renderFiles();
  });

  /* ── Resize ── */
  window.addEventListener('resize', function () {
    var n = window.innerWidth < 760;
    if (n !== narrow) { narrow = n; renderFiles(); }
  });

  /* ── Init ── */
  renderFiles();
})();
